### ISSUE TITLE
Not find the 'models' 

### ISSUE THREAD

**Issue by zszq777** [ccccchenllll/SGT_master#1]
I hope you're doing well. I am working on reproducing the results from your paper, but it appears that the code provided is missing the models folder. I would also like to ask for your advice regarding the data preprocessing procedures involved.
I would really appreciate your help with these questions when you have a moment.
Thank you so much for your time, and I look forward to hearing from you.

**Comment by ccccchenllll** [comment]
> I hope you're doing well. I am working on reproducing the results from your paper, but it appears that the code provided is missing the models folder. I would also like to ask for your advice regarding the data preprocessing procedures involved. I would really appreciate your help with these questions when you have a moment. Thank you so much for your time, and I look forward to hearing from you.

I'm sorry that I missed the **model.py** when I uploaded the code. I've been a bit busy lately, so I'll reorganize the code and data and upload it when I have some free time.

**Comment by ccccchenllll** [comment]
> I hope you're doing well. I am working on reproducing the results from your paper, but it appears that the code provided is missing the models folder. I would also like to ask for your advice regarding the data preprocessing procedures involved. I would really appreciate your help with these questions when you have a moment. Thank you so much for your time, and I look forward to hearing from you.

I'm sorry that I missed  **model.py** when I uploaded the code. I've been a bit busy lately, so I'll reorganize the code and data and upload it when I have some free time.

**Comment by zszq777** [comment]
> > I hope you're doing well. I am working on reproducing the results from your paper, but it appears that the code provided is missing the models folder. I would also like to ask for your advice regarding the data preprocessing procedures involved. I would really appreciate your help with these questions when you have a moment. Thank you so much for your time, and I look forward to hearing from you.
> 
> I'm sorry that I missed **model.py** when I uploaded the code. I've been a bit busy lately, so I'll reorganize the code and data and upload it when I have some free time.
Thank you for your understanding regarding this matter.
I look forward to receiving the updated code soon, and I’m eager for your guidance, especially regarding the data preprocessing procedures. If I have any questions, I will reach out to you promptly. Thanks again for your help!

**Comment by zszq777** [comment]
> > 我希望你一切顺利。我正在努力重现您论文的结果，但似乎提供的代码缺少 models 文件夹。我还想询问您有关所涉及的数据预处理程序的建议。我非常感谢您有空时对这些问题的帮助。非常感谢您抽出时间接受采访，我期待着您的来信。
> 
> 很抱歉，我在上传代码时错过了 **model.py**。我最近有点忙，所以我会重新整理代码和数据，并在有空闲时间时上传。

Thank you for your understanding regarding this matter.
I look forward to receiving the updated code soon, and I’m eager for your guidance, especially regarding the data preprocessing procedures. If I have any questions, I will reach out to you promptly. Thanks again for your help!

**Comment by ccccchenllll** [comment]
> > > 我希望你一切顺利。我正在努力重现您论文的结果，但似乎提供的代码缺少 models 文件夹。我还想询问您有关所涉及的数据预处理程序的建议。我非常感谢您有空时对这些问题的帮助。非常感谢您抽出时间接受采访，我期待着您的来信。
> > 
> > 
> > 很抱歉，我在上传代码时错过了 **model.py**。我最近有点忙，所以我会重新整理代码和数据，并在有空闲时间时上传。
> 
> Thank you for your understanding regarding this matter. I look forward to receiving the updated code soon, and I’m eager for your guidance, especially regarding the data preprocessing procedures. If I have any questions, I will reach out to you promptly. Thanks again for your help!



> > > 我希望你一切顺利。我正在努力重现您论文的结果，但似乎提供的代码缺少 models 文件夹。我还想询问您有关所涉及的数据预处理程序的建议。我非常感谢您有空时对这些问题的帮助。非常感谢您抽出时间接受采访，我期待着您的来信。
> > 
> > 
> > 很抱歉，我在上传代码时错过了 **model.py**。我最近有点忙，所以我会重新整理代码和数据，并在有空闲时间时上传。
> 
> Thank you for your understanding regarding this matter. I look forward to receiving the updated code soon, and I’m eager for your guidance, especially regarding the data preprocessing procedures. If I have any questions, I will reach out to you promptly. Thanks again for your help!

Thank you for your understanding. I have uploaded the model folder. Please check it.

**Comment by ccccchenllll** [comment]
> > > 我希望你一切顺利。我正在努力重现您论文的结果，但似乎提供的代码缺少 models 文件夹。我还想询问您有关所涉及的数据预处理程序的建议。我非常感谢您有空时对这些问题的帮助。非常感谢您抽出时间接受采访，我期待着您的来信。
> > 
> > 
> > 很抱歉，我在上传代码时错过了 **model.py**。我最近有点忙，所以我会重新整理代码和数据，并在有空闲时间时上传。
> 
> Thank you for your understanding regarding this matter. I look forward to receiving the updated code soon, and I’m eager for your guidance, especially regarding the data preprocessing procedures. If I have any questions, I will reach out to you promptly. Thanks again for your help!

Thank you for your understanding. I have uploaded the model folder. Please check it. And the processed data is quite large and difficult to upload. If you need the dataset, you can email me. Thx!

**Comment by zszq777** [comment]
> > > > 我希望你一切顺利。我正在努力重现您论文的结果，但似乎提供的代码缺少 models 文件夹。我还想询问您有关所涉及的数据预处理程序的建议。我非常感谢您有空时对这些问题的帮助。非常感谢您抽出时间接受采访，我期待着您的来信。
> > > 
> > > 
> > > 很抱歉，我在上传代码时错过了 **model.py**。我最近有点忙，所以我会重新整理代码和数据，并在有空闲时间时上传。
> > 
> > 
> > Thank you for your understanding regarding this matter. I look forward to receiving the updated code soon, and I’m eager for your guidance, especially regarding the data preprocessing procedures. If I have any questions, I will reach out to you promptly. Thanks again for your help!
> 
> Thank you for your understanding. I have uploaded the model folder. Please check it. And the processed data is quite large and difficult to upload. If you need the dataset, you can email me. Thx!

Hello, could you please send me the processed dataset via email? My email address is 332405080492@zzuli.edu.cn. I would also like to discuss some details regarding the dataset processing with you. Additionally, I am unable to download the pre-trained model using the address you provided, likely due to access permission issues. Thank you very much for your help!

**Comment by ccccchenllll** [comment]
> > > > > 我希望你一切顺利。我正在努力重现您论文的结果，但似乎提供的代码缺少 models 文件夹。我还想询问您有关所涉及的数据预处理程序的建议。我非常感谢您有空时对这些问题的帮助。非常感谢您抽出时间接受采访，我期待着您的来信。
> > > > 
> > > > 
> > > > 很抱歉，我在上传代码时错过了 **model.py**。我最近有点忙，所以我会重新整理代码和数据，并在有空闲时间时上传。
> > > 
> > > 
> > > Thank you for your understanding regarding this matter. I look forward to receiving the updated code soon, and I’m eager for your guidance, especially regarding the data preprocessing procedures. If I have any questions, I will reach out to you promptly. Thanks again for your help!
> > 
> > 
> > Thank you for your understanding. I have uploaded the model folder. Please check it. And the processed data is quite large and difficult to upload. If you need the dataset, you can email me. Thx!
> 
> Hello, could you please send me the processed dataset via email? My email address is [332405080492@zzuli.edu.cn](mailto:332405080492@zzuli.edu.cn). I would also like to discuss some details regarding the dataset processing with you. Additionally, I am unable to download the pre-trained model using the address you provided, likely due to access permission issues. Thank you very much for your help!

处理过的数据已经发到您的邮箱。关于模型获取，您可以挂个梯子

**Comment by zszq777** [comment]
> > > > > > 我希望你一切顺利。我正在努力重现您论文的结果，但似乎提供的代码缺少 models 文件夹。我还想询问您有关所涉及的数据预处理程序的建议。我非常感谢您有空时对这些问题的帮助。非常感谢您抽出时间接受采访，我期待着您的来信。
> > > > > 
> > > > > 
> > > > > 很抱歉，我在上传代码时错过了 **model.py**。我最近有点忙，所以我会重新整理代码和数据，并在有空闲时间时上传。
> > > > 
> > > > 
> > > > Thank you for your understanding regarding this matter. I look forward to receiving the updated code soon, and I’m eager for your guidance, especially regarding the data preprocessing procedures. If I have any questions, I will reach out to you promptly. Thanks again for your help!
> > > 
> > > 
> > > Thank you for your understanding. I have uploaded the model folder. Please check it. And the processed data is quite large and difficult to upload. If you need the dataset, you can email me. Thx!
> > 
> > 
> > Hello, could you please send me the processed dataset via email? My email address is [332405080492@zzuli.edu.cn](mailto:332405080492@zzuli.edu.cn). I would also like to discuss some details regarding the dataset processing with you. Additionally, I am unable to download the pre-trained model using the address you provided, likely due to access permission issues. Thank you very much for your help!
> 
> 处理过的数据已经发到您的邮箱。关于模型获取，您可以挂个梯子

![微信图片_20241127170215](https://github.com/user-attachments/assets/b6fff12e-05c2-455e-bc33-ce790ef94cf6)
您好，感谢您的帮助，根据您提供的预训练模型的地址，点进入之后有上述图片的内容，
![微信图片_20241127170926](https://github.com/user-attachments/assets/a77a35ac-af81-4c96-89b0-70eb6ee8d8aa)
但是我这边并没有收到电子邮箱的权限告知，如果您方便的话，我这边也可以用百度网盘或其他途径进行传输；再次感谢您的帮助！

**Comment by ccccchenllll** [comment]
给你发邮箱吧，请查收

**Comment by zszq777** [comment]
> 给你发邮箱吧，请查收

非常感谢您的帮助！！！
