### ISSUE TITLE
No such file frame045_adjacency_matrix.npy'

### ISSUE THREAD

**Issue by 3485006134** [ccccchenllll/SGT_master#2]
Hello, this problem occurred when I was reproducing your code
FileNotFoundError: [Errno 2] No such file or directory:'C:\\Users\\kuchi\\SGT_master\\data\\EndoVis_2018\\instruments18_caption\\instruments18_caption\\seq_2/features/frame045_adjacency_matrix.npy'
Can we talk about it? Or please give me your email

**Comment by ccccchenllll** [comment]
> Hello, this problem occurred when I was reproducing your code FileNotFoundError: [Errno 2] No such file or directory:'C:\Users\kuchi\SGT_master\data\EndoVis_2018\instruments18_caption\instruments18_caption\seq_2/features/frame045_adjacency_matrix.npy' Can we talk about it? Or please give me your email

I processed the original dataset to generate the adjacency matrix.
